# Generated by Django 5.2.1 on 2025-05-26 02:10

from django.db import migrations, models

def move_bio_to_user(apps, schema_editor):
    Profile = apps.get_model('muckd', 'Profile')
    User = apps.get_model('muckd', 'User')
    
    for profile in Profile.objects.all():
        if profile.bio:
            user = profile.user
            user.bio = profile.bio
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('muckd', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='unset location', max_length=100),
        ),
        migrations.RunPython(move_bio_to_user),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
