# Generated by Django 5.2.1 on 2025-05-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muckd', '0003_remove_profile_bio_user_bio_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
