# Generated by Django 5.2.1 on 2025-05-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muckd', '0006_alter_post_image_alter_profile_profile_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
