# Generated by Django 5.2.1 on 2025-05-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muckd', '0007_user_last_location_update_alter_user_email_and_more'),
        ('muckd', '0008_alter_user_location'),
    ]

    operations = [
    ]
