# Generated by Django 5.2.1 on 2025-05-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muckd', '0009_convert_location_to_json'),
        ('muckd', '0009_merge_20250526_2256'),
    ]

    operations = [
    ]
