# Generated by Django 5.2.1 on 2025-05-27 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muckd', '0011_fix_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_sharing_mode',
            field=models.CharField(choices=[('invisible', 'Invisible'), ('all_friends', 'All Friends'), ('select_friends', 'Select Friends')], default='all_friends', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_friends',
            field=models.ManyToManyField(blank=True, related_name='can_see_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
