version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-temporary-key-for-build-only
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - STATIC_ROOT=/app/staticfiles
      - STATIC_URL=/static/
      - DB_NAME=muckd
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - muckd_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=muckd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - muckd_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - muckd_network

  celery:
    build: .
    command: celery -A muckd worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-temporary-key-for-build-only
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - STATIC_ROOT=/app/staticfiles
      - STATIC_URL=/static/
      - DB_NAME=muckd
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - muckd_network

  celery-beat:
    build: .
    command: celery -A muckd beat -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-temporary-key-for-build-only
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - STATIC_ROOT=/app/staticfiles
      - STATIC_URL=/static/
      - DB_NAME=muckd
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - muckd_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  muckd_network:
    driver: bridge 